name: Release

on:
  pull_request:

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          tag: "0.0.3"
          body: "release test3"
          makeLatest: "latest"
          generateReleaseNotes: "false"
